services:
  server:
    image: node:22-alpine3.18
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: npm run start:dev

  db:
    image: mysql:5.7
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env